### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by marcus7777**
[Review on Reviewable](https://reviewable.io/reviews/metanov/gold-password-input/7)

### CODE REVIEW

**Comment by GeoloeG-IsT** [comment]
@marcus7777 this element is needed for the `reveal` option! :)

**Comment by MeTaNoV** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/metanov/gold-password-input/7)*

**Comment by marcus7777** [comment]
but you delete the repo

**Comment by GeoloeG-IsT** [comment]
`bower info toggle-icon`, I reintegrated the author original version that has been patched! :)

**Comment by GeoloeG-IsT** [comment]
I forgot to do a new release... sorry for the confusion: https://github.com/MeTaNoV/gold-password-input/releases/tag/1.1.1

**Comment by marcus7777** [comment]
thanks updating

**Pull request closed without merging**
